export const OPTIONAL_HEADER_TO_COLUMN: Record<string, string> = {
  issuedate: 'issue_date',
  month: 'month',
  year: 'year',
  customer: 'customer',
  projectname: 'project_name',
  subcontractno: 'sub_contract_no',
  projectcode: 'project_code',
  milestone: 'milestone',
  sitecode: 'site_code',
  sitename: 'site_name',
  siteid: 'site_id',
  qcstatus: 'qc_status',
  approverlevel: 'approver_level',
  shipmentnumber: 'shipment_number',
  lineno: 'line_no',
  department: 'department',
  /** CSV header e.g. "Department name" → normalizeLineHeader → departmentname */
  departmentname: 'department',
  subdepartment: 'sub_department',
  uom: 'uom',
  poquantity: 'po_quantity',
  startdate: 'start_date',
  enddate: 'end_date',
  poinvoiced: 'po_invoiced',
  poacceptanceapproved: 'po_acceptance_approved',
  poacceptancepending: 'po_acceptance_pending',
  acceptancerejectedamount: 'acceptance_rejected_amount',
  wnd: 'wnd',
  pendingtoapply: 'pending_to_apply',
  milestonestatus: 'milestone_status',
  postatus: 'po_status',
  confirmationstatus: 'confirmation_status',
  pendingmilestone: 'pending_milestone',
  acceptancestatus: 'acceptance_status',
  rejectionremarks: 'rejection_remarks',
};
